#!/bin/bash -x
/usr/libexec/qemu-kvm -monitor stdio \
-serial none \
-parallel none \
-enable-kvm \
-name "guest" \
-m 1024 \
-mem-prealloc \
-usb \
-device usb-ehci,id=ehci \
-machine pc,accel=kvm,kernel_irqchip=on,mem-merge=off \
-cdrom ${HOME}/Downloads/$1 \
-boot order=d \
-device usb-tablet \
-vnc :1
