#!/bin/bash -x
sudo apt-get -y install squashfs-tools xorriso grub-pc-bin grub-efi-amd64 syslinux syslinux-utils
(
echo "useradd knoppix"
echo "apt-get -y install --no-install-recommends \
    network-manager net-tools wireless-tools wpagui \
    curl openssh-client \
    xfce4 xserver-xorg-core xserver-xorg xinit xterm \
    nano lightdm"
) | sudo chroot $HOME/LIVE_BOOT/$1/chroot
(
echo "apt-get clean"
echo "dpkg-reconfigure lightdm"
) | sudo chroot $HOME/LIVE_BOOT/$1/chroot

sudo mkdir -p $HOME/LIVE_BOOT/$1/chroot/etc/sddm.conf.d
sudo chmod a+w $HOME/LIVE_BOOT/$1/chroot/etc/sddm.conf.d
sed 's/#autologin-user=/autologin-user=knoppix/' <$HOME/LIVE_BOOT/$1/chroot/etc/lightdm/lightdm.conf |
  sed 's/#autologin-user-timeout/autologin-user-timeout/' >/tmp/lightdm.conf.1
sudo cp /tmp/lightdm.conf.1 $HOME/LIVE_BOOT/$1/chroot/etc/lightdm/lightdm.conf
rm -fr $HOME/LIVE_BOOT/$1/image $HOME/LIVE_BOOT/$1/scratch
mkdir -p $HOME/LIVE_BOOT/$1/image/live $HOME/LIVE_BOOT/$1/scratch
sudo mksquashfs $HOME/LIVE_BOOT/$1/chroot $HOME/LIVE_BOOT/$1/image/live/filesystem.squashfs -e boot
cp $HOME/LIVE_BOOT/$1/chroot/boot/vmlinuz-* \
    $HOME/LIVE_BOOT/$1/image/vmlinuz
cp $HOME/LIVE_BOOT/$1/chroot/boot/initrd.img-* \
    $HOME/LIVE_BOOT/$1/image/initrd

cat <<'EOF' >$HOME/LIVE_BOOT/$1/scratch/grub.cfg

search --set=root --file /DEBIAN_CUSTOM

insmod all_video

set default="0"
set timeout=30

menuentry "Debian Live" {
    linux /vmlinuz boot=live quiet nomodeset
    initrd /initrd
}
EOF

touch $HOME/LIVE_BOOT/$1/image/DEBIAN_CUSTOM
grub-mkstandalone \
    --format=x86_64-efi \
    --output=$HOME/LIVE_BOOT/$1/scratch/bootx64.efi \
    --locales="" \
    --fonts="" \
    "boot/grub/grub.cfg=$HOME/LIVE_BOOT/$1/scratch/grub.cfg"
(cd $HOME/LIVE_BOOT/$1/scratch && \
    dd if=/dev/zero of=efiboot.img bs=1M count=10 && \
    sudo mkfs.vfat efiboot.img && \
    mmd -i efiboot.img efi efi/boot && \
    mcopy -i efiboot.img ./bootx64.efi ::efi/boot/
)
grub-mkstandalone \
    --format=i386-pc \
    --output=$HOME/LIVE_BOOT/$1/scratch/core.img \
    --install-modules="linux normal iso9660 biosdisk memdisk search tar ls" \
    --modules="linux normal iso9660 biosdisk search" \
    --locales="" \
    --fonts="" \
    "boot/grub/grub.cfg=$HOME/LIVE_BOOT/$1/scratch/grub.cfg"
cat \
    /usr/lib/grub/i386-pc/cdboot.img \
    $HOME/LIVE_BOOT/$1/scratch/core.img \
> $HOME/LIVE_BOOT/$1/scratch/bios.img
xorriso \
    -as mkisofs \
    -iso-level 3 \
    -full-iso9660-filenames \
    -volid "DEBIAN_CUSTOM" \
    -eltorito-boot \
        boot/grub/bios.img \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        --eltorito-catalog boot/grub/boot.cat \
    --grub2-boot-info \
    --grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
    -eltorito-alt-boot \
        -e EFI/efiboot.img \
        -no-emul-boot \
    -append_partition 2 0xef ${HOME}/LIVE_BOOT/$1/scratch/efiboot.img \
    -output "${HOME}/LIVE_BOOT/$1/debian-custom.iso" \
    -isohybrid-mbr /usr/lib/syslinux/isohdpfx.bin \
    -graft-points \
        "${HOME}/LIVE_BOOT/$1/image" \
        /boot/grub/bios.img=$HOME/LIVE_BOOT/$1/scratch/bios.img \
        /EFI/efiboot.img=$HOME/LIVE_BOOT/$1/scratch/efiboot.img

