#!/bin/bash
mkdir -p $HOME/LIVE_BOOT/$1/chroot
cp $1.list $HOME/LIVE_BOOT/$1/chroot/
sudo debootstrap \
    --arch=amd64 \
    --variant=minbase \
    buster \
    $HOME/LIVE_BOOT/$1/chroot \
    http://ftp.us.debian.org/debian/
(
echo "echo debian-live >/etc/hostname"
echo "apt-get update"
echo "apt-get install -y --no-install-recommends linux-image-amd64 live-boot systemd-sysv"
) | sudo chroot $HOME/LIVE_BOOT/$1/chroot/

