#!/bin/bash -x
cp lists/$1.list $HOME/LIVE_BOOT/$1/chroot/tmp/pkgs.list
cp scripts/target_install $HOME/LIVE_BOOT/$1/chroot/tmp/
sudo chroot $HOME/LIVE_BOOT/$1/chroot /tmp/target_install
rm $HOME/LIVE_BOOT/$1/chroot/tmp/pkgs.list
rm $HOME/LIVE_BOOT/$1/chroot/tmp/target_install
