#!/bin/bash -x
sed 's/ main/ main non-free contrib/' </etc/apt/sources.list >/tmp/sources.list
cp /tmp/sources.list /etc/apt/sources.list
rm /tmp/sources.list
apt-get update
for p in $(</tmp/pkgs.list)
do apt-get -d -y install $p
done
for p in $(</tmp/pkgs.list)
do apt-get -y install $p
done
