#!/bin/bash -x
sed -i 's/ main/ main non-free contrib/' /etc/apt/sources.list
apt-get update
mount -t proc /proc
for p in $(</tmp/pkgs.list)
do apt-get -d -y install $p
done
for p in $(</tmp/pkgs.list)
do apt-get -y install $p
done
umount /proc
